export const KONVA = {
  DEFAULT_SCALE: 1,
  MIN_SCALE: 0.3,
  MAX_SCALE: 3,
  WHEEL_SENSITIVITY: 0.95,
  ZOOM_STEP: 1.2,
  DRAG_THRESHOLD: 5,
  SELECTION_STROKE_WIDTH: 4,
  HIGHLIGHT_STROKE_WIDTH: 3,
  DEFAULT_STROKE_WIDTH: 1,
} as const;